# Generated by Django 5.2.1 on 2025-06-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_cliente_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_vendaa',
            new_name='data_venda',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
